### ISSUE TITLE
Make sure code isn't Java8

### ISSUE THREAD

**Issue by Ghosts** [doughepi/program-5#12]
I'm not sure, but it's possible some of the channel methods for temp file creation might be Java8, also worth checking if the temp file solution will work on whatever computer they run tests on.

I'm guessing they just run tests manually?

**Comment by Ghosts** [comment]
Forget I ever tried using temporary files.
I was not thinking.

**Comment by doughepi** [comment]
Leo said that the TA is going to download and run manually, so I think we're good.
