### ISSUE TITLE
Would be cool to do an animated background.

### ISSUE THREAD

**Issue by Ghosts** [doughepi/program-5#14]
- http://codepen.io/Munkkeli/pen/PqWBdP
- http://codepen.io/html5andblog/pen/jWbLbj
- http://codepen.io/elomatreb/pen/RNrzgN
- http://codepen.io/andrewsuniverse/pen/wBdZXb

Something subtle that matches the feel.

What do you think?

**Comment by doughepi** [comment]
I agree. The first one is nice.
