### ISSUE TITLE
Server crashes when any number greater than Integer.MAX is entered into the quantity fields.

### ISSUE THREAD

**Issue by doughepi** [doughepi/program-5#16]

**Comment by Ghosts** [comment]
Doesn't crash, just doesn't load the order update.
Will limit form input + something or another.

**Comment by Ghosts** [comment]
Lol okay so it works now, but there might be a better way to fix it.

**Comment by doughepi** [comment]
Nah, it's fine for now. Eventually it should be handled server-side though.
